# Generated by Django 5.0.7 on 2026-06-19 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_is_featured_product_seller_product_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='store_type',
            field=models.CharField(choices=[('admin', 'Admin Store'), ('seller', 'Seller')], default='seller', max_length=10),
        ),
    ]
