# Generated by Django 5.0.7 on 2026-06-13 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_address_user_birthdate_user_city_user_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='can_add_products',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_seller',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='seller_is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='seller_type',
            field=models.CharField(choices=[('basic', 'Basic'), ('approved', 'Approved'), ('trusted', 'Trusted')], default='basic', max_length=20),
        ),
    ]
